# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Music Assistant Alexa API add-on
version: "1.3.0-beta.1"
slug: ma_alexa_api
description: Music Assistant Alexa API add-on
url: "https://github.com/timlaing/music-assistant-alexa-api/tree/main/music-assistant-alexa-api"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/timlaing/{arch}-addon-ma-alexa-api"
ingress: true
ingress_entry: /status
panel_icon: mdi:music
homeassistant: 2025.12.5
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "The API port"
